#!/usr/bin/env python3
"""Export a trained SAC (continuous) Channel-Dodge actor to dodge-policy.js.

Sibling of export_dodge_weights.py (which handles the discrete PPO actor). SAC's
actor is a SquashedGaussianActor — a ReLU MLP ``271 -> 256 -> 256 -> 4`` whose
first 2 outputs are the Gaussian mean (the last 2 are log-std, inference-irrelevant).
Greedy action = ``tanh(mean)`` clamped to the unit disk, which the JS in
channel-dodge.html does when ``DODGE_POLICY.continuous`` is set.

Packed float32 blob layout (little-endian, the order the JS reads):
    net.0.weight [256,271], net.0.bias [256],
    net.2.weight [256,256], net.2.bias [256],
    net.4.weight [4,256]  , net.4.bias [4]

    python tools/export_dodge_sac.py --ckpt ../../RainbowDQN/runs/sac_gpu_smooth/best.pt \
        --version sac_gpu_smooth
"""

import argparse
import base64
import os
import sys

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
WEB_ROOT = os.path.dirname(HERE)                                  # …/SkyZeroWeb
RAINBOW = os.path.normpath(os.path.join(WEB_ROOT, "..", "..", "RainbowDQN"))  # …/RL/RainbowDQN

# SquashedGaussianActor.net = _mlp(271, (256,256), 4): Linear,ReLU,Linear,ReLU,Linear
LAYERS = [
    ("net.0.weight", "net.0.bias", 271, 256, "relu"),
    ("net.2.weight", "net.2.bias", 256, 256, "relu"),
    ("net.4.weight", "net.4.bias", 256, 4,   "linear"),   # 4 = mean(2) + logstd(2)
]
OBS_DIM = LAYERS[0][2]
ACT_DIM = 2
HIDDEN = (256, 256)


def _forward_numpy(blob, x):
    off = 0
    h = np.asarray(x, dtype=np.float32)
    for _wk, _bk, n_in, n_out, act in LAYERS:
        W = blob[off:off + n_out * n_in].reshape(n_out, n_in); off += n_out * n_in
        b = blob[off:off + n_out];                              off += n_out
        h = W @ h + b
        if act == "relu":
            h = np.maximum(h, 0.0)
    return h


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ckpt", default=os.path.join(RAINBOW, "runs", "sac_gpu_smooth", "best.pt"))
    ap.add_argument("--out", default=os.path.join(WEB_ROOT, "dodge-policy.js"))
    ap.add_argument("--version", default="sac_gpu_smooth")
    args = ap.parse_args()

    if not os.path.exists(args.ckpt):
        sys.exit(f"[export] checkpoint not found: {args.ckpt}")
    ck = torch.load(args.ckpt, map_location="cpu")
    if "actor" not in ck:
        sys.exit("[export] not a SAC checkpoint (no 'actor' key)")
    obs_shape = tuple(ck.get("obs_shape", ()))
    if obs_shape and obs_shape != (OBS_DIM,):
        sys.exit(f"[export] expected obs_shape ({OBS_DIM},), got {obs_shape}")

    sd = ck["actor"]
    parts = []
    for wk, bk, n_in, n_out, _act in LAYERS:
        W = sd[wk].detach().cpu().numpy().astype(np.float32)
        b = sd[bk].detach().cpu().numpy().astype(np.float32)
        assert W.shape == (n_out, n_in), f"{wk}: {W.shape} != {(n_out, n_in)}"
        assert b.shape == (n_out,), f"{bk}: {b.shape} != {(n_out,)}"
        parts.append(W.reshape(-1)); parts.append(b)
    blob = np.concatenate(parts).astype("<f4")

    # --- self-check: packed-blob mean MUST match the real torch actor mean ---
    sys.path.insert(0, RAINBOW)
    from sac_net import SquashedGaussianActor  # noqa: E402
    actor = SquashedGaussianActor(OBS_DIM, ACT_DIM, HIDDEN)
    actor.load_state_dict(sd); actor.eval()
    rng = np.random.default_rng(0)
    max_err = 0.0
    for _ in range(64):
        x = rng.standard_normal(OBS_DIM).astype(np.float32)
        with torch.no_grad():
            mu = actor._mean_logstd(torch.from_numpy(x).unsqueeze(0))[0].squeeze(0).numpy()
        got = _forward_numpy(blob, x)[:ACT_DIM]
        max_err = max(max_err, float(np.abs(mu - got).max()))
    if max_err > 1e-3:
        sys.exit(f"[export] SELF-CHECK FAILED: max mean err {max_err:.2e}")

    b64 = base64.b64encode(blob.tobytes()).decode("ascii")
    arch_js = ", ".join(f'[{ni}, {no}, "{act}"]' for _, _, ni, no, act in LAYERS)
    js = f"""// AUTO-GENERATED by tools/export_dodge_sac.py — DO NOT EDIT BY HAND.
// Trained SAC Channel-Dodge actor (continuous): obs 271 -> 256 -> 256 -> 4 (relu),
// outputs[:2] = Gaussian mean; greedy move = tanh(mean) clamped to the unit disk.
// Source checkpoint: {os.path.relpath(args.ckpt, WEB_ROOT)}   version: {args.version}
window.DODGE_POLICY = {{
  version: {args.version!r},
  obsDim: {OBS_DIM},
  continuous: true,
  actDim: {ACT_DIM},
  // [in, out, activation] per layer, in packed order:
  arch: [{arch_js}],
  weightsB64: "{b64}",
}};
"""
    with open(args.out, "w") as f:
        f.write(js)
    print(f"[export] {args.ckpt}")
    print(f"[export]   self-check OK (64 inputs, max mean err {max_err:.1e})")
    print(f"[export]   wrote {args.out}  ({blob.nbytes/1024:.0f} KB float32 -> {len(js)/1024:.0f} KB js)")
    print(f"[export] >>> bump cache-bust in channel-dodge.html to:")
    print(f'[export] >>>   <script src="dodge-policy.js?v={args.version}"></script>')


if __name__ == "__main__":
    main()
